---
title: Buenos días!
---
 
**Espero que todos os encontréis bien.
Me han preguntado por actividades o ejercicios físicos que vuestros hij@s
pueden realizar en casa. Se que es complicado para vosotr@s por la falta de
espacio, y además hay niñ@s que son muy tranquil@s pero hay otr@s que
necesitan descargar esa energía.
Os mando enlaces de vídeos para que hagáis cosas sencillas en casa.
Una cosa que les gusta mucho son los vídeos de baile de just dance. Hay
muchísimos en youTube y es una manera de hacer ejercicio muy activo y
ameno sin necesidad de mucho espacio.**
<br>

### Contenido virtual

1.[video](https://www.youtube.com/watch?v=gCzgc_RelBA)
2.[video](https://www.youtube.com/watch?v=AV1biKT426I)
3.[video](https://www.youtube.com/watch?v=fq0GqiO-B74)

**Estos son algunos enlaces de apoyo de ejercicios que podéis hacer en casa
también:**

4.[video](https://www.youtube.com/watch?v=zYhzTHw5-7o)
5.[video](https://www.youtube.com/watch?v=mEOC33G3KAg)
6.[video](https://www.youtube.com/watch?v=L_A_HjHZxfI)

**También podéis hacer ejercicios más calmados como el yoga. Igualmente hay
un montón de vídeos que os pueden servir de guía. Estos ejercicios servirán
para relajar y controlar un poco la energía. Os paso enlaces:**

7.[video](https://www.youtube.com/watch?v=3bjggxDiXyk)
8.[video](https://www.youtube.com/watch?v=O-ze3CxuTMU)
9.[video](https://www.youtube.com/watch?v=t8748OWc1nQ)

**Espero que todo esto os sirva para poder pasar estos momentos.
De todos modos seguiré en contacto con vosotros.
Ya sabéis que cualquier consulta o duda aquí podéis encontrarme.
Un saludo.
Chus**